### ISSUE TITLE
Plugin doesn't work with Moodle 3.2?

### ISSUE THREAD

**Issue by jstilwell** [LafColITS/moodle-local_course_template#9]
Hello, I can install this plugin in Moodle 3.2 but it doesn't seem to function correctly. It's not really throwing any useful errors -- but appears to just not work. I've tried on a couple of different sites (same environments)

Environment:

App: Moodle 3.2.6
OS: CentOS Linux release 7.4.1708 (Core) 
Web Server: Apache/2.4.6 (CentOS)
PHP: PHP 7.0.26
DB Server: MariaDB 5.5.56

**Comment by mackensen** [comment]
Could you please post the regular expressions that you're using and some sample idnumbers?

**Comment by cthelen** [comment]
I have tried this on my Mac laptop using Moodle 3.1, and it worked like a champ.  I'm trying it again with Moodle 3.2, and again it seems to work as advertised.
Environment:
App: Moodle 3.2.7 (Build: 20180115)
OS: MacOS 10.11.6 (15G19009)
database : mysql (5.5.42)
MAMP: 3.4
PHP: 5.6.10
Web Server: Apache/2.2.29 (Unix) 
Term Code: /([0-9]{2})[0-9]{4}/
Template shortname format: Template-[TERMCODE]
Template Course Shortname: Template-11
Course ID #: 111111
It worked the first time.

jstillwell, can you post your Term Code, Template Shortname Format, Template Course Shortname and Course ID that caused no error and no success?

Cheers!
Carl Thelen

**Comment by jstilwell** [comment]
Term code: /[0-9]+\.([0-9]+)/
Template shortname format: Template-[TERMCODE]

ID number we used was test.201710. 

Revisiting, it was likely the use of the letters in the course ID versus numbers that was the issue.

**Comment by heather-williams** [comment]
We see an error that flashes by very quickly and was unnoticeable until we did some further digging, as it doesn't print to error log either. When we create a new course that should use the template and hit save, this flashes by very quickly:

{code}
Exception encountered in event observer '\local_course_template\observers::course_created': Coding error detected, it must be fixed by a programmer: A lock was created but not released at: /mnt/code/www/moodle_prod/local/course_template/classes/observers.php on line 34 Code should look like: $factory = \core\lock\lock_config::get_lock_factory('type'); $lock = $factory->get_lock(Resource id #578); $lock->release(); // Locks must ALWAYS be released like this.
	•	line 36 of /local/course_template/classes/observers.php: call to core\lock\lock->__destruct()
	•	line ? of unknownfile: call to local_course_template\observers::course_created()
	•	line 155 of /lib/classes/event/manager.php: call to call_user_func()
	•	line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
	•	line 834 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
	•	line 2347 of /course/lib.php: call to core\event\base->trigger()
	•	line 157 of /course/edit.php: call to create_course()
{code}

Any thoughts on what might be causing this? I can get it to work on my test site, so I think it's something unique here. Not sure what though....

**Comment by mackensen** [comment]
@heather-williams usually, though not always, there's a different error which happens right before the lock error which causes Moodle to not finish executing the command, which means the lock isn't released. It's a symptom, not a cause.

**Comment by heather-williams** [comment]
@mackensen Yeah I know, that lock error usually means something else is going on. I guess I was hoping the stack trace might help you, because there are no other errors that we can see. I'll do some more digging and come back around.
